server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gpt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123888
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    host: 192.168.11.203
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
    timeout: 100s

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
#idea配置文件默认不允许有中文注释
logging:
  level:
    com.example.demo.dao: debug

#  代理ip和端口
http:
  proxy:
    ip: 127.0.0.1
    port: 4780

#腾讯云短信注册

#chatGpt  密钥
chatgpt:
  secretkey: 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









